---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netdevice-driver
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netdevice-driver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netdevice-driver
subjects:
- kind: ServiceAccount
  name: netdevice-driver
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netdevice-driver
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netdevice-driver
  namespace: kube-system
  labels:
    tier: node
    app: netdevice-driver
    k8s-app: netdevice-driver
spec:
  selector:
    matchLabels:
      app: netdevice-driver
  template:
    metadata:
      labels:
        tier: node
        app: netdevice-driver
        k8s-app: netdevice-driver
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: netdevice-driver
      initContainers:
      - name: install-cdi-bin
        image: aojea/netdevice-driver:v0.1.0
        command: ['sh', '-c', 'cd /opt/cdi/bin; for i in * ; do cat $i > /cdi/$i ; chmod +x /cdi/$i ; done']
        volumeMounts:
        - name: cdi-bin
          mountPath: /cdi
      containers:
      - name: netdevice-driver
        args:
        - /plugin
        - -interfaces
        - dummy
        - -v
        - "4"
        image: aojea/netdevice-driver:v0.1.0
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: cdi
          mountPath: /var/run/cdi
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
          type: DirectoryOrCreate
      - name: cdi
        hostPath:
          path: /var/run/cdi
          type: DirectoryOrCreate
      - name: cdi-bin
        hostPath:
          path: /opt/cdi/bin
          type: DirectoryOrCreate
---
