apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    kni: netdevice
spec:
  containers:
  - name: nginx
    command: [ "/bin/sh" ]
    args: [ "-c","sleep 300000"]
    image: gcr.io/kubernetes-e2e-test-images/agnhost:2.8
    ports:
    - containerPort: 80
    resources:
      limits:
         networking.k8s.io/netdevice: 1
